### ISSUE TITLE
Support YPub and ZPub

### ISSUE THREAD

**Issue by dasilvarosa** [LedgerHQ/app-bitcoin-legacy#55]
Please add support to generate both xpub, ypub and zpub.

**Comment by joevegan** [comment]
Yes please add support and until you do put a note not to used the xpub key as they are broken on the live app

**Comment by Zwilla** [comment]
vote

**Comment by super-e** [comment]
Indeed would be useful

**Comment by super-e** [comment]
A possible work-around if you want to get the ZPUB for your native segwit wallet is to connect the Ledger to Electrum and check the wallet's information. I tested then importing into Samourai Sentinel and worked beautifully.

**Comment by IMExperts** [comment]
vote

**Comment by guzelonur** [comment]
As of 2024, LL still shows xpub for Segwit and Native Segwit accounts incorrectly. 

Can someone explain in which format LL shows Segwit and Native Segwit accounts' so-called "**xpub**" string?

For Segwit **ypub**, and for Native Segwit **zpub** required in advanced logs. But LL developers haven't implemented it yet!

Hope someone pays attention to this crucial, but a very simple task implementation which is _still_ absent in Bitcoin app.

**Comment by bigspider** [comment]
This was maybe a good idea in 2018, but now that bitcoin moved towards wallets based on [output descriptors](https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md), ypub/zpub formats should be considered obsolete.

Software wallets should rather backup the entire descriptor, and descriptors only support xpubs.

**Comment by guzelonur** [comment]
@bigspider 
Thanks for the reply Salvatore. And thanks for the information about descriptors.

Assuming you're also referring to other "software" wallets like Electrum as you used the term "_software wallet_" in your reply, and we know LL is just a _frontend_ app of Ledger _hardware_ wallet. Just verifying my understanding of terminology.

However, many posts (including on Reddit) are still stating _difficulty and massive distress_ about viewing correct Segwit/Native Segwit transaction history and balance (shows either blank or incomplete on LL interface when you reinstall/reset the OS and the app) and the people are still recommended to use that tool written by Jameson Lopp to see the entire transaction history and balance **manually**, here:
https://jlopp.github.io/xpub-converter/

Apart from displaying xpub entry in a Segwit account, so, at least the integrity of that tool might be integrated on LL (along with details sections of Segwit Bitcoin accounts, of course with the courtesy of author) in which my point of view, it would be _very_ handy and useful. As either on Bitcointalk.org, Reddit and even Github have such mixed old and recent posts mentioning about this problem.

Implementing this feature in LL interface could have cleared the confusion of seeing _xpub_ for Segwit/Native Segwit account details instead of _ypub/zpub_ values.

Best Regards.
